In [5]:
! cd /Users/narrik/mlpractical/; python setup.py install

running install
running bdist_egg
running egg_info
writing mlp.egg-info/PKG-INFO
writing dependency_links to mlp.egg-info/dependency_links.txt
writing top-level names to mlp.egg-info/top_level.txt
reading manifest file 'mlp.egg-info/SOURCES.txt'
writing manifest file 'mlp.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.9-x86_64/egg
running install_lib
running build_py
copying mlp/layers.py -> build/lib/mlp
creating build/bdist.macosx-10.9-x86_64/egg
creating build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/penalties.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/initialisers.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/optimisers.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/test_methods.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/models.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying build/lib/mlp/__init__.py -> build/bdist.macosx-10.9-x86_64/egg/mlp
copying bu

In [1]:
from mlp.test_methods import test_leaky_relu
import numpy as np

fprop_test, fprop_output, fprop_correct, \
bprop_test, bprop_output, bprop_correct = test_leaky_relu()

assert fprop_test == 1.0, (
'The leaky relu fprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct, fprop_output, fprop_output-fprop_correct)
)

print("Leaky ReLU Fprop Functionality Test Passed")

assert bprop_test == 1.0, (
'The leaky relu bprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct, bprop_output, bprop_output-bprop_correct)
)

print("Leaky ReLU Bprop Test Passed")

Leaky ReLU Fprop Functionality Test Passed
Leaky ReLU Bprop Test Passed


In [2]:
from mlp.test_methods import test_random_relu

fprop_test_arg_leakiness, fprop_output_arg_leakiness, fprop_correct_arg_leakiness, \
bprop_test_arg_leakiness, bprop_output_arg_leakiness, bprop_correct_arg_leakiness, \
fprop_test_rng_leakiness, fprop_output_rng_leakiness, fprop_correct_rng_leakiness, \
bprop_test_rng_leakiness, bprop_output_rng_leakiness, bprop_correct_rng_leakiness = test_random_relu()

assert fprop_test_arg_leakiness == 1.0, (
'The random relu fprop functionality when given an argument leakiness test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct_arg_leakiness, fprop_output_arg_leakiness, fprop_output_arg_leakiness-fprop_correct_arg_leakiness)
)

print("Random ReLU Fprop when given an argument leakiness Functionality Test Passed")

assert bprop_test_arg_leakiness == 1.0, (
'The random relu bprop functionality when given an argument leakiness test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct_arg_leakiness, bprop_output_arg_leakiness, bprop_output_arg_leakiness-bprop_correct_arg_leakiness)
)

print("Random ReLU Bprop when using an argument leakiness Functionality Test Passed")

assert fprop_test_rng_leakiness == 1.0, (
'The random relu fprop functionality when given an argument leakiness test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct_rng_leakiness, fprop_output_rng_leakiness, fprop_output_rng_leakiness-fprop_correct_rng_leakiness)
)

print("Random ReLU Fprop when using rng leakiness Functionality Test Passed")

assert bprop_test_rng_leakiness == 1.0, (
'The random relu bprop functionality when given rng leakiness test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct_rng_leakiness, bprop_output_rng_leakiness, bprop_output_rng_leakiness-bprop_correct_rng_leakiness)
)

print("Random ReLU Bprop when using rng leakiness Functionality Passed")


Random ReLU Fprop when given an argument leakiness Functionality Test Passed
Random ReLU Bprop when using an argument leakiness Functionality Test Passed
Random ReLU Fprop when using rng leakiness Functionality Test Passed
Random ReLU Bprop when using rng leakiness Functionality Passed


In [3]:
from mlp.test_methods import test_parametric_relu

fprop_test, fprop_output, fprop_correct, \
bprop_test, bprop_output, bprop_correct, \
grads_wrt_param_test, grads_wrt_param_output, grads_wrt_param_correct = test_parametric_relu()

assert fprop_test == 1.0, (
'The parametric relu fprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct, fprop_output, fprop_output-fprop_correct)
)

print("Parametric ReLU Fprop Functionality Test Passed")

assert grads_wrt_param_test == 1.0, (
'The parametric relu grad_wrt_param functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(grads_wrt_param_correct, grads_wrt_param_output, grads_wrt_param_output-grads_wrt_param_correct)
)

print("Parametric ReLU Grads wrt Params Test Passed")

assert bprop_test == 1.0, (
'The parametric relu bprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct, bprop_output, bprop_output-bprop_correct)
)

print("Parametric ReLU Bprop Test Passed")



Parametric ReLU Fprop Functionality Test Passed
Parametric ReLU Grads wrt Params Test Passed
Parametric ReLU Bprop Test Passed


In [4]:
from mlp.test_methods import test_exponential_linear_unit


fprop_test, fprop_output, fprop_correct, \
bprop_test, bprop_output, bprop_correct = test_exponential_linear_unit()


assert fprop_test == 1.0, (
'The random relu fprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(fprop_correct, fprop_output, fprop_output-fprop_correct)
)

print("ELU Fprop Functionality Test Passed")

assert bprop_test == 1.0, (
'The random relu bprop functionality test failed'
'Correct output is \n\n{0}\n\n but returned output is \n\n{1}\n\n difference is \n\n{2}'
.format(bprop_correct, bprop_output, bprop_output-bprop_correct, bprop_output/bprop_correct)
)



print("ELU Bprop Test Passed")

ELU Fprop Functionality Test Passed
ELU Bprop Test Passed


In [3]:
a = np.random.randint(-2.0, 2.0, size=(10000, 10000))
print(a)

[[ 0  1  1 ...  1 -1 -2]
 [-2 -2  1 ... -2  1 -1]
 [ 1  0  0 ...  0  0  1]
 ...
 [ 0 -2  0 ... -1  0 -1]
 [-2  1 -1 ...  0  1 -1]
 [-2 -1  1 ...  0 -2  0]]


In [14]:
%%timeit -n 10 -r 3
a[a <= 0] *=2

1.09 s ± 11.1 ms per loop (mean ± std. dev. of 3 runs, 10 loops each)


In [15]:
%%timeit -n 10 -r 3
np.where(a > 0, a, 2*a)

973 ms ± 5.59 ms per loop (mean ± std. dev. of 3 runs, 10 loops each)


In [16]:
%%timeit -n 10 -r 3
da = np.ones_like(a)
da[a <= 0] = 0.2

713 ms ± 13 ms per loop (mean ± std. dev. of 3 runs, 10 loops each)


In [17]:
%%timeit -n 10 -r 3
np.where(a > 0, 1, 0.2)

595 ms ± 3.86 ms per loop (mean ± std. dev. of 3 runs, 10 loops each)
